version: '3'

services:
  apache_img:
    container_name: apache
    build:
      context: ./
      dockerfile: ./docker/apache/Dockerfile
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
    volumes:
      - ./logs/apache:${APACHE_ROOT_DIR}/logs
      - ./html:/var/www/html
      - /var/www/html/wdelo30/wcl_euroizol/composer/vendor
    ports:
      - ${APACHE_EXPOSED_PORT}:80
    networks:
      public_net:
        ipv4_address: ${APACHE_IP}
    environment:
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
      - PHP_IP=${PHP_IP}
      - PHP_APP_DIR=${PHP_APP_DIR}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}
  php_img:
    container_name: php
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      args:
        - WEB_USER=${WEB_USER}
        - WEB_GROUP=${WEB_GROUP}
        - PHP_ROOT_DIR=${PHP_ROOT_DIR}
    working_dir: ${PHP_APP_DIR}
    volumes:
      - ./html:${PHP_APP_DIR}
      - ../logs/php:${PHP_ROOT_DIR}/logs
    depends_on:
      - apache_img
    networks:
      public_net:
        ipv4_address: ${PHP_IP}
    environment:
      - PHP_ROOT_DIR=${PHP_ROOT_DIR}
      - APACHE_IP=${APACHE_IP}
      - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
      - WEB_USER=${WEB_USER}
      - WEB_GROUP=${WEB_GROUP}

networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}